spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/civiconnect?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=11032005
# JPA properties
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#logging.level.org.springframework.orm.hibernate5=DEBUG

spring.security.user.name=admin
spring.security.user.password=admin123

#RazorPay API Key
razorpay.key_id= rzp_test_e4OMejQFQ7EH39
razorpay.key_secret= HOPdeuA5dakEZFeAo6N8H47k

#JWT Secret key for signing n Verification 
SECRET_KEY=1uORMccTFcTWQvjupAGxGapKFtcSRb4IPAaUJpfxbQoXuHutABXbNdt74yAg4SvofyvqSY6MXcbwoTXp7gk2Q3jIjOjsaUAUz4xA+7OHU4w=
#JWT expiration timeout in msec : 24*3600*1000
EXP_TIMEOUT=86400000

#Mail service related
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khajamoinuddin7442@gmail.com
spring.mail.password=khjmnddn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true